theme: jekyll-theme-minimal
title: The Wizardry of Good Movies <img src="https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/44d44b26187031.56352e766c7e0.png" width="50" height="50" alt="Wizards Cap">
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
